import examples.interface_analysis.Interface_1_critical_elements_test
import examples.interface_analysis.Interface_2_sphere_of_influence_test
import examples.interface_analysis.Interface_3_feedback_loops_test
import examples.interface_analysis.Interface_4_recursive_elements_test
import examples.interface_analysis.Interface_5_absence_of_items_test
import examples.interface_analysis.Interface_6_unused_items_test
